name: 'Doka Labeler'
description: 'Automatically label new pull requests based on the paths of files being changed'
author: 'Doka'

inputs:
  token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  config:
    description: 'The path for the label configurations'
    default: '.github/labeler.yml'
    required: true
  strategy:
    description: 'How to apply matched labels: "append" - to add matched labels on top of already assigned; "replace" - replace currently assigned labels with new.'
    default: 'append'
    required: false

branding:
  icon: 'tag'
  color: 'gray-dark'

runs:
  using: 'node12'
  main: 'dist/index.js'
